steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/mail-doc-search-system:latest'
      - '-f'
      - 'services/doc-search/Dockerfile'
      - '.'
    dir: '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/mail-doc-search-system:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mail-doc-search-system'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/mail-doc-search-system:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '3600'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/mail-doc-search-system:latest'

timeout: 1200s
